sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - docker build -t madnight/docker-wkhtmltopdf-aas .
  - docker run -d -p 127.0.0.1:80:5555 madnight/docker-wkhtmltopdf-aas
  - pip install requests

script:
  - sudo docker ps | grep -q madnight
  - python test.py
