sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y poppler-utils bash
  - docker build -t test-service .
  - docker run -d -e API_TOKEN='travisci-test123456789' -p 127.0.0.1:80:5555 --name test-service test-service
  - pip install requests

script:
  - docker ps | grep -q test-service
  - bash test.sh
  - pdftotext -layout test.pdf - | grep -q "Hello World"
  - pdftotext -layout test.pdf - | grep -q "Lorem ipsum"
  - bash -c '! pdftotext -layout test.pdf - | grep -q "False"'
  - python test.py
